/* Synthesized drum kit + chord pad for MPK pads.
   All sounds generated by Web Audio — no samples. */
const Drums = (() => {
  function ctx() { return Synth.ctx(); }

  function kick() {
    const c = ctx(); const t = c.currentTime;
    const o = c.createOscillator();
    const g = c.createGain();
    o.frequency.setValueAtTime(150, t);
    o.frequency.exponentialRampToValueAtTime(40, t + 0.15);
    g.gain.setValueAtTime(1, t);
    g.gain.exponentialRampToValueAtTime(0.001, t + 0.4);
    o.connect(g).connect(c.destination);
    o.start(t); o.stop(t + 0.5);
  }

  function snare() {
    const c = ctx(); const t = c.currentTime;
    // noise
    const buf = c.createBuffer(1, c.sampleRate * 0.2, c.sampleRate);
    const d = buf.getChannelData(0);
    for (let i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1;
    const n = c.createBufferSource(); n.buffer = buf;
    const f = c.createBiquadFilter(); f.type = 'highpass'; f.frequency.value = 1500;
    const g = c.createGain();
    g.gain.setValueAtTime(0.8, t);
    g.gain.exponentialRampToValueAtTime(0.001, t + 0.2);
    n.connect(f).connect(g).connect(c.destination);
    // body
    const o = c.createOscillator(); o.type = 'triangle'; o.frequency.value = 200;
    const og = c.createGain(); og.gain.setValueAtTime(0.6, t);
    og.gain.exponentialRampToValueAtTime(0.001, t + 0.15);
    o.connect(og).connect(c.destination);
    n.start(t); n.stop(t + 0.2);
    o.start(t); o.stop(t + 0.2);
  }

  function hat(open = false) {
    const c = ctx(); const t = c.currentTime;
    const len = open ? 0.3 : 0.05;
    const buf = c.createBuffer(1, c.sampleRate * len, c.sampleRate);
    const d = buf.getChannelData(0);
    for (let i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1;
    const n = c.createBufferSource(); n.buffer = buf;
    const f = c.createBiquadFilter(); f.type = 'highpass'; f.frequency.value = 7000;
    const g = c.createGain();
    g.gain.setValueAtTime(0.3, t);
    g.gain.exponentialRampToValueAtTime(0.001, t + len);
    n.connect(f).connect(g).connect(c.destination);
    n.start(t); n.stop(t + len);
  }

  function clap() {
    const c = ctx(); const t = c.currentTime;
    for (let i = 0; i < 3; i++) {
      const delay = i * 0.015;
      const buf = c.createBuffer(1, c.sampleRate * 0.08, c.sampleRate);
      const d = buf.getChannelData(0);
      for (let j = 0; j < d.length; j++) d[j] = Math.random() * 2 - 1;
      const n = c.createBufferSource(); n.buffer = buf;
      const f = c.createBiquadFilter(); f.type = 'bandpass'; f.frequency.value = 1200;
      const g = c.createGain();
      g.gain.setValueAtTime(0.5, t + delay);
      g.gain.exponentialRampToValueAtTime(0.001, t + delay + 0.08);
      n.connect(f).connect(g).connect(c.destination);
      n.start(t + delay); n.stop(t + delay + 0.1);
    }
  }

  function tom(freq = 120) {
    const c = ctx(); const t = c.currentTime;
    const o = c.createOscillator(); o.type = 'sine';
    o.frequency.setValueAtTime(freq * 1.5, t);
    o.frequency.exponentialRampToValueAtTime(freq, t + 0.2);
    const g = c.createGain();
    g.gain.setValueAtTime(0.7, t);
    g.gain.exponentialRampToValueAtTime(0.001, t + 0.4);
    o.connect(g).connect(c.destination);
    o.start(t); o.stop(t + 0.5);
  }

  function crash() {
    const c = ctx(); const t = c.currentTime;
    const buf = c.createBuffer(1, c.sampleRate * 1.2, c.sampleRate);
    const d = buf.getChannelData(0);
    for (let i = 0; i < d.length; i++) d[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / d.length, 2);
    const n = c.createBufferSource(); n.buffer = buf;
    const f = c.createBiquadFilter(); f.type = 'highpass'; f.frequency.value = 5000;
    const g = c.createGain(); g.gain.setValueAtTime(0.4, t);
    g.gain.exponentialRampToValueAtTime(0.001, t + 1.2);
    n.connect(f).connect(g).connect(c.destination);
    n.start(t); n.stop(t + 1.2);
  }

  // Pad grid: 8 drums mapped to pads 1..8 of Bank A.
  // Mapped to MPK Mini Mk3 default pad note numbers (C1..G1 = 36..43).
  const MAP = {
    36: { name: 'Kick',     fn: () => kick() },
    37: { name: 'Snare',    fn: () => snare() },
    38: { name: 'Cl Hat',   fn: () => hat(false) },
    39: { name: 'Op Hat',   fn: () => hat(true) },
    40: { name: 'Clap',     fn: () => clap() },
    41: { name: 'Lo Tom',   fn: () => tom(90) },
    42: { name: 'Hi Tom',   fn: () => tom(180) },
    43: { name: 'Crash',    fn: () => crash() },
  };

  function trigger(midi) {
    if (!ctx()) Synth.init();
    if (MAP[midi]) MAP[midi].fn();
  }

  function metronomeClick(accent = false) {
    const c = ctx(); const t = c.currentTime;
    const o = c.createOscillator(); o.type = 'square';
    o.frequency.value = accent ? 1600 : 1000;
    const g = c.createGain();
    g.gain.setValueAtTime(accent ? 0.25 : 0.15, t);
    g.gain.exponentialRampToValueAtTime(0.001, t + 0.05);
    o.connect(g).connect(c.destination);
    o.start(t); o.stop(t + 0.06);
  }

  return { trigger, MAP, kick, snare, hat, clap, crash, tom, metronomeClick };
})();
